apiVersion: v1
kind: Service
metadata:
    name: app-pstember
    namespace: training-row-pstember
spec:
    ports:
    - name: "8765"
    port: 8765
    targetPort: 3000
    nodePort: 30001 #port exposed on localhost
    selector:
    app: app-pstember
    type: LoadBalancer